window.EVENTS_META = {"guncelleme": "2026-10-08"};
window.EVENTS = [
  {
    "tur": "etkinlik",
    "ad": "BİLİMFEST İZMİR",
    "tarih": "2026-10-08",
    "tarih_bitis": "2026-10-10",
    "yer": "Agora AVM, İzmir",
    "aciklama": "Yapay zekâdan robotik teknolojilere kadar pek çok alanda 80'den fazla etkileşimli atölye ve bilim etkinliği gerçekleştirilmektedir.",
    "link": "https://www.izmirdesondakika.com.tr/bilimfest-izmir-yarin-kapilarini-aciyor",
    "kaynak": "Bilimfest İzmir, yarın kapılarını açıyor - İzmir'de Son Dakika Haber",
    "bolge": "yakin",
    "ucret": "ucretsiz",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Oksijen Future Forum 2026 | AFTER AI",
    "tarih": "2026-10-12",
    "tarih_bitis": "2026-10-12",
    "yer": null,
    "aciklama": "Geleceğin teknolojilerini yapay zeka odağında ele alan meet-up etkinliğidir.",
    "link": "https://coderspace.io/etkinlikler/oksijen-future-forum-2026-after-ai/",
    "kaynak": "En Popüler 10 Yazılım Discord Sunucusu | Yazılım Geliştiriciler için Topluluklar",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Minds Mastering Machines - M3: LLMs im Unternehmen",
    "tarih": "2026-10-15",
    "tarih_bitis": "2026-10-15",
    "yer": null,
    "aciklama": "Die Mastering AI ist der Treffpunkt für Fachleute, die KI in die technische Realität umsetzen. Schwerpunkte der Konferenz sind 2027 u.a. Agentic AI, AI Engineering, GenAI und AI Security.",
    "link": "https://m3-konferenz.de/llm.php",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "2nd International Conference on Artificial Intelligence and Big Data Analytics",
    "tarih": "2026-10-15",
    "tarih_bitis": "2026-10-16",
    "yer": "Singapore, Singapore",
    "aciklama": "Artificial intelligence conference, big data analytics conference, AI and big data congress, international AI conference, machine learning conference, data science conference, deep learning summit, AI research…",
    "link": "https://vartusconferences.com/aibda",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "X-Ops Conference Dubai",
    "tarih": "2026-10-15",
    "tarih_bitis": "2026-10-17",
    "yer": "Dubai, United Arab Emirates",
    "aciklama": "El mayor evento de DevOps, DevSecOps, AIOps, MLOps y Platform Engineering en España. Madrid 2026 · Dubai 2026 · Summit + Conference.",
    "link": "https://xopsconference.com",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "AI Business Series",
    "tarih": "2026-10-15",
    "tarih_bitis": "2026-10-15",
    "yer": null,
    "aciklama": "Pazarlama, finans ve mühendislik dünyasında yapay zekânın dönüşüm gücünün ele alındığı online etkinlik serisidir.",
    "link": "https://coderspace.io/etkinlikler/ai-business-series/",
    "kaynak": "En Popüler 10 Yazılım Discord Sunucusu | Yazılım Geliştiriciler için Topluluklar",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "AWS - Cloud Türkiye AI/MCP Meetup",
    "tarih": "2026-10-15",
    "tarih_bitis": "2026-10-15",
    "yer": "İTÜ Bilgisayar ve Bilişim Fakültesi, İstanbul",
    "aciklama": "AWS ve Cloud Türkiye topluluğu tarafından düzenlenen yapay zeka odaklı teknik buluşmadır.",
    "link": "https://kommunity.com/cloud-turkiye/events/aws-cloud-turkiye-aimcp-meetup-0cb93259",
    "kaynak": "Events from Cloud Türkiye - Kommunity",
    "bolge": "turkiye",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "MIT AI Conference",
    "tarih": "2026-10-17",
    "tarih_bitis": "2026-10-17",
    "yer": "Mountain View, CA, U.S.A.",
    "aciklama": "500+ AI leaders. One high-signal day. Keynotes, panels, workshops & demos. Oct 17, 2026 · Computer History Museum · Mountain View, CA. Register now — limited seats.",
    "link": "https://www.mitaiconference.org",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "TechEx Europe",
    "tarih": "2026-10-19",
    "tarih_bitis": "2026-10-20",
    "yer": "Amsterdam, Netherlands",
    "aciklama": null,
    "link": "https://techexevent.com/europe",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "AMTSO Cyber Research Conference",
    "tarih": "2026-10-20",
    "tarih_bitis": "2026-10-21",
    "yer": "Brussels, Belgium",
    "aciklama": "The AMTSO Cyber Research Conference 2026 is planned for October 20-21 2026 in Brussels, Belgium.",
    "link": "https://www.amtso.org/special-events/amtso-cyber-research-conference-2026",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "swampUP Europe",
    "tarih": "2026-10-20",
    "tarih_bitis": "2026-10-22",
    "yer": "Barcelona, Spain",
    "aciklama": "Join swampUP Europe 2026 in Barcelona (Oct 20–22): JFrog's premier DevOps, DevSecOps, and AI software supply chain conference.",
    "link": "https://swampup.jfrog.com/europe",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "All Day AI",
    "tarih": "2026-10-22",
    "tarih_bitis": "2026-10-22",
    "yer": null,
    "aciklama": "A free, live, virtual conference for teams and practitioners applying AI across development, leadership, security, and business functions.",
    "link": "https://www.alldayai.com",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "DevOpsDays Istanbul 2026",
    "tarih": "2026-10-23",
    "tarih_bitis": "2026-10-24",
    "yer": "Dedeman Bostancı Hotel & Convention Center, İstanbul",
    "aciklama": "DevOps Türkiye topluluğu tarafından düzenlenen, yazılım geliştirme ve operasyon profesyonellerini buluşturan konferanstır.",
    "link": "https://kommunity.com/devops-turkiye/events/devopsdays-istanbul-2026-ae573533",
    "kaynak": "DevOpsDays Istanbul 2026 - Kommunity",
    "bolge": "turkiye",
    "ucret": "ucretli",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "diger",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "AI DevCon NYC",
    "tarih": "2026-11-02",
    "tarih_bitis": "2026-11-04",
    "yer": "Brooklyn, NY, U.S.A.",
    "aciklama": "The best place to master agentic coding, helping developers and organisations build with agents",
    "link": "https://tessl.io/devcon",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Nullcon Berlin",
    "tarih": "2026-11-02",
    "tarih_bitis": "2026-11-06",
    "yer": "Berlin, Germany",
    "aciklama": "Experience Nullcon Berlin 2026 with expert talks, hands-on trainings, CTFs, and interactive villages. Connect with the global security community in Berlin this November.",
    "link": "https://nullcon.net/event/nullcon-berlin-2026",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "The AI Conf",
    "tarih": "2026-11-03",
    "tarih_bitis": "2026-11-04",
    "yer": "Barcelona, Spain",
    "aciklama": "3rd-4th November 2026, Barcelona, Spain. 2 Days. Get your tickets now!",
    "link": "https://theconf.ai",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "S2N: Storage Server Network",
    "tarih": "2026-11-03",
    "tarih_bitis": "2026-11-04",
    "yer": "Berlin, Germany",
    "aciklama": "S2N – Storage, Server, Network. Der Treffpunkt für alle IT-Profis mit Interesse an Backup & Recovery, Servertechnik und IT-Netzwerken",
    "link": "https://s2n.heise.de",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "YÖK Dijital Üniversite Platformu Ortak Açılış Dersi",
    "tarih": "2026-11-03",
    "tarih_bitis": "2026-11-03",
    "yer": null,
    "aciklama": "Yapay zekâ, veri analizi ve sürdürülebilirlik alanlarında 16 modüllü ücretsiz eğitim programının ortak açılış dersidir.",
    "link": "https://www.yok.gov.tr/en",
    "kaynak": "Yükseköğretim Kurulunun Veri Analizi Okulu, Dijital Üniversite Platformuna dönüşüyor",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Uluslararası Sempozyum | Algoritmalar Çağında İnsan: Sosyal Bilimlerde Yapay Zeka ve Geleceğin İnşası",
    "tarih": "2026-11-04",
    "tarih_bitis": "2026-11-06",
    "yer": "Ege Üniversitesi, İzmir",
    "aciklama": "Sosyal bilimlerde yapay zeka kullanımı ve geleceğin inşasını ele alan uluslararası sempozyumdur.",
    "link": "https://duyuru.ege.edu.tr",
    "kaynak": "Gelecek Duyurular - EGE Duyuru - Ege Üniversitesi",
    "bolge": "yakin",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "hibrit",
    "kategori": "yapay-zeka",
    "dogrulanmadi": true
  },
  {
    "tur": "etkinlik",
    "ad": "Unhacked 360 Germany: FutureSec Summit",
    "tarih": "2026-11-09",
    "tarih_bitis": "2026-11-10",
    "yer": "Berlin, Germany",
    "aciklama": "oin global leaders at Unhacked 360 Germany: FutureSec Summit (Nov 9–10, 2026). Explore AI in cybersecurity, threat defense, and digital innovation. Register now!",
    "link": "https://momentera.org/conference/unhacked-360-germany-futuresec-world-summit",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Türkiye Yapay Zeka Zirvesi 2026",
    "tarih": "2026-11-11",
    "tarih_bitis": "2026-11-12",
    "yer": "Wyndham Grand İstanbul Levent & Online",
    "aciklama": "Ajanlar Aramızda temasıyla yapay zeka ajanlarının iş dünyasındaki kullanımına odaklanan zirvedir.",
    "link": "https://www.chip.com.tr/haber/turkiye-yapay-zeka-zirvesinin-2026-programi-belli-oldu_184451.html",
    "kaynak": "Türkiye Yapay Zeka Zirvesi 11-12 Kasım'da düzenlenecek. Bu yılın odağında yapay zeka ajanları var - CHIP Online",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "bilinmiyor",
    "format": "hibrit",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "AI Engineering Summit",
    "tarih": "2026-11-16",
    "tarih_bitis": "2026-11-20",
    "yer": "Berlin, Germany",
    "aciklama": "Der AI Engineering Summit zeigt, wie Enterprise Software Teams Coding Agents, AI Workflows, Security, Governance, Qualitätssicherung und Legacy Modernization produktiv einsetzen.",
    "link": "https://ai-engineering-summit.de",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "MLCon Berlin",
    "tarih": "2026-11-16",
    "tarih_bitis": "2026-11-20",
    "yer": "Berlin, Germany",
    "aciklama": "The Event for Machine Learning Technologies & Innovations.",
    "link": "https://mlconference.ai/berlin",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "NextGen Intelligence Conference: Data, Cloud & AI",
    "tarih": "2026-11-16",
    "tarih_bitis": "2026-11-17",
    "yer": "London, U.K.",
    "aciklama": "Join industry leaders in London for the NextGen Intelligence Conference on Data, Cloud & AI. Explore GenAI, machine learning, big data, and cloud innovation.",
    "link": "https://techaiconf.com",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "API Conference Berlin",
    "tarih": "2026-11-16",
    "tarih_bitis": "2026-11-20",
    "yer": "Berlin, Germany",
    "aciklama": "November 16 ‒ 20, 2026 | Berlin | API Conference offers many exciting sessions, keynotes & workshops for API Developers! Get your ticket now!",
    "link": "https://apiconference.net/berlin",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Building the Modern World with the Power of Data",
    "tarih": "2026-11-17",
    "tarih_bitis": "2026-11-17",
    "yer": "Tech Istanbul | Şişhane, İstanbul",
    "aciklama": "Veri odaklı teknolojiler ve modern dünya uygulamalarına odaklanan Cloud Türkiye etkinliğidir.",
    "link": "https://kommunity.com/cloud-turkiye/events/building-the-modern-world-with-the-power-of-data-081d61d1",
    "kaynak": "Events from Cloud Türkiye - Kommunity",
    "bolge": "turkiye",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "diger",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "AI World Congress",
    "tarih": "2026-11-25",
    "tarih_bitis": "2026-11-26",
    "yer": "London, U.K.",
    "aciklama": "AI Conference in London UK is the AI World Congress 2026 on November 25th-26th. Join the premier AI Conference for professionals from across the AI Events 2026 AI ecosystem. Leading Artificial Intelligence Conference on…",
    "link": "https://aiconference.london",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "bilinmiyor",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Workplace Ninjas India",
    "tarih": "2026-11-27",
    "tarih_bitis": "2026-11-28",
    "yer": "Delhi, India",
    "aciklama": "Two days of Microsoft Modern Workplace learning, community, and networking in New Delhi.",
    "link": "https://www.wpninjas-india.com",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "ESPC",
    "tarih": "2026-11-30",
    "tarih_bitis": "2026-12-03",
    "yer": "Amsterdam, Netherlands",
    "aciklama": "Join us at ESPC26 in Amsterdam, Netherlands. Hear from the best Microsoft 365 and AI, SharePoint, Teams, Power Platform & Azure experts.",
    "link": "https://www.sharepointeurope.com",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "IT Security Summit Munich",
    "tarih": "2026-11-30",
    "tarih_bitis": "2026-12-04",
    "yer": "Munich, Germany",
    "aciklama": "2 days conference + 2 days workshops & sessions: Learn about the latest trends and technologies for more IT security in your company. Meet renowned experts who share their knowledge and experience...",
    "link": "https://it-security-summit.com/munich",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Future of CISO & Awards 2026",
    "tarih": "2026-12-03",
    "tarih_bitis": "2026-12-03",
    "yer": "Çırağan Palace Kempinski, İstanbul",
    "aciklama": "Siber güvenlik liderlerini, yapay zekâ güvenliği ve kurumsal risk yönetişimi gündemiyle bir araya getiren zirvedir.",
    "link": "https://lostar.com.tr/etkinlikler/future-of-ciso-2026/",
    "kaynak": "Siber Güvenlik Etkinlikleri ve Webinarları 2026| Lostar",
    "bolge": "turkiye",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "DevFest Izmir 2026",
    "tarih": "2026-12-04",
    "tarih_bitis": "2026-12-05",
    "yer": "MMO Tepekule Kongre, Sergi ve İş Merkezi, İzmir",
    "aciklama": "Yapay zekâdan mobil geliştirmeye kadar güncel konuların ele alındığı İzmir'in en büyük teknoloji buluşmasıdır.",
    "link": "https://kommunity.com/gdg-izmir/events/devfest-izmir-2026-16cae32b",
    "kaynak": "DevFest Izmir 2026 - Kommunity",
    "bolge": "yakin",
    "ucret": "ucretsiz",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "IT-Tage",
    "tarih": "2026-12-07",
    "tarih_bitis": "2026-12-10",
    "yer": "Frankfurt am Main, Germany",
    "aciklama": "Die IT-Konferenz mit großer Bandbreite: Software-Architektur & -Design, Software- Entwicklung, Datenbanken, DevOps, Cloud, IT-Security, Agile, KI, Open Source und Souveränität.",
    "link": "https://www.it-tage.org",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "Great International AI Native Summit (GAINS)",
    "tarih": "2026-12-09",
    "tarih_bitis": "2026-12-10",
    "yer": "Bangalore, India",
    "aciklama": "GIDS is one of Asia-Pacific’s biggest and longest running software engineering conferences, bringing together developers, architects, engineering leaders, and platform teams building modern systems at scale. From…",
    "link": "https://ainativesummit.com",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "AI for Developers",
    "tarih": "2026-12-17",
    "tarih_bitis": "2026-12-18",
    "yer": null,
    "aciklama": "Where best developers and top companies connect.",
    "link": "https://aiconference.dev",
    "kaynak": "confs.tech",
    "bolge": "global",
    "ucret": "bilinmiyor",
    "sertifika": "bilinmiyor",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "etkinlik",
    "ad": "DevFest Istanbul 2026",
    "tarih": "2026-12-18",
    "tarih_bitis": "2026-12-19",
    "yer": "Wyndham Grand Istanbul Levent, İstanbul",
    "aciklama": "Yapay zeka, bulut, web ve mobil teknolojilere odaklanan topluluk destekli geliştirici konferansıdır.",
    "link": "https://kommunity.com/gdg-istanbul/events/devfest-istanbul-2026-55458e85",
    "kaynak": "DevFest Istanbul 2026 - Kommunity",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "bilinmiyor",
    "format": "yuzyuze",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "egitim",
    "ad": "Siber Güvenliğe Giriş",
    "tarih": null,
    "tarih_bitis": null,
    "yer": null,
    "aciklama": "Siber güvenlik kavramları, tehditler ve alt alanlar hakkında temel seviye çevrim içi eğitimdir.",
    "link": "https://www.btkakademi.gov.tr/portal/course/siber-guvenlige-giris-27928",
    "kaynak": "Siber Güvenliğe Giriş - BTK Akademi",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "online",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "egitim",
    "ad": "Ağ Temelleri ve Güvenliği",
    "tarih": null,
    "tarih_bitis": null,
    "yer": null,
    "aciklama": "Ağ mimarisi ve ağ güvenliği konularını orta seviyede ele alan çevrim içi eğitimdir.",
    "link": "https://www.btkakademi.gov.tr/portal/course/ag-temelleri-ve-guvenligi-68038",
    "kaynak": "BTK Akademi E-Devlet ile Giriş Kılavuzu",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "online",
    "kategori": "siber",
    "dogrulanmadi": false
  },
  {
    "tur": "egitim",
    "ad": "Getting Started with Generative AI",
    "tarih": null,
    "tarih_bitis": null,
    "yer": null,
    "aciklama": "Üretken yapay zekanın temel kavramlarını, etik ilkelerini ve büyük dil modellerini öğreten dijital sertifikalı eğitimdir.",
    "link": "https://skills.yourlearning.ibm.com/activity/PLAN-BAEFCCAAD520?lang=tr",
    "kaynak": "IBM SkillsBuild Öğrenim Kataloğu | Ücretsiz Yapay Zeka, Siber Güvenlik, Veri ve Teknoloji Kursları",
    "bolge": "global",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": true
  },
  {
    "tur": "egitim",
    "ad": "Siber Güvenliği Keşfetme",
    "tarih": null,
    "tarih_bitis": null,
    "yer": null,
    "aciklama": "Siber güvenliğin temel ilkeleri ve siber saldırılara karşı korunma yöntemlerini sunan modüldür.",
    "link": "https://skills.yourlearning.ibm.com/activity/ALM-COURSE_3825251?lang=tr",
    "kaynak": "IBM SkillsBuild Öğrenim Kataloğu | Ücretsiz Yapay Zeka, Siber Güvenlik, Veri ve Teknoloji Kursları",
    "bolge": "global",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "online",
    "kategori": "siber",
    "dogrulanmadi": true
  },
  {
    "tur": "egitim",
    "ad": "Üretken Yapay Zekaya Giriş",
    "tarih": null,
    "tarih_bitis": null,
    "yer": null,
    "aciklama": "Büyük dil modellerinden sorumlu yapay zeka ilkelerine kadar üretken yapay zeka kavramlarını öğreten Türkçe eğitimdir.",
    "link": "https://www.skills.google/paths/118?locale=tr&utm_source=grow&utm_medium=referral&utm_campaign=gwg-ai-for-all-tr",
    "kaynak": "Yapay Zeka Eğitimleri: Yapay Zeka Becerilerinizi Geliştirin - Grow with Google",
    "bolge": "global",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": true
  },
  {
    "tur": "egitim",
    "ad": "Veri Bilimi ve Yapay Zekaya Giriş",
    "tarih": null,
    "tarih_bitis": null,
    "yer": null,
    "aciklama": "Veri bilimi ve yapay zeka konularına günlük hayattan uygulamalar ile giriş yapılan sertifikalı online eğitimdir.",
    "link": "https://gelecegiyazanlar.turkcell.com.tr/egitimler/veri-bilimi-ve-yapay-zekaya-giris",
    "kaynak": "Veri Bilimi ve Yapay Zekaya Giriş | Geleceği Yazanlar",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "online",
    "kategori": "yapay-zeka",
    "dogrulanmadi": false
  },
  {
    "tur": "egitim",
    "ad": "Tech Masters Bootcamp Programı",
    "tarih": null,
    "tarih_bitis": null,
    "yer": null,
    "aciklama": "Yazılım, yapay zeka, veri bilimi ve siber güvenlik alanlarında online, canlı ve ücretsiz öğrenme maratonudur.",
    "link": "https://www.techcareer.net/techmasters",
    "kaynak": "Tech Master Bootcamp Eğitimleri - Techcareer.net",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "online",
    "kategori": "diger",
    "dogrulanmadi": false
  },
  {
    "tur": "egitim",
    "ad": "Siber Vatan Yetkinlik Merkezi Siber Güvenlik Eğitimleri",
    "tarih": null,
    "tarih_bitis": null,
    "yer": "Kayseri Büyükşehir Belediyesi Bilişim Akademisi",
    "aciklama": "CEH ve CCNA sertifika programlarına yönelik uygulamalı yüz yüze siber güvenlik eğitimidir.",
    "link": "https://dmyo.kayseri.edu.tr/tr/duyuru-detay/10353/muafiyet-sinavina-girecek-ogrencilerin-dikkatine",
    "kaynak": "SİBER VATAN YETKİNLİK MERKEZİ EĞİTİM BİLGİLENDİRMESİ",
    "bolge": "turkiye",
    "ucret": "ucretsiz",
    "sertifika": "var",
    "format": "yuzyuze",
    "kategori": "siber",
    "dogrulanmadi": false
  }
];
